<script lang="ts">
	import { language } from '$lib/stores';
	import { onMount } from 'svelte';

	import Section from '$lib/components/Section.svelte';
	import LandingPage from '$lib/components/LandingPage.svelte';
	import Paragraph from '$lib/components/Paragraph.svelte';
	import Navbar from '$lib/components/Navbar.svelte';
	import Footer from '$lib/components/Footer.svelte';
	import Parallax from '$lib/components/Parallax.svelte';

	//@ts-ignore
	import Stripe from '$lib/assets/stripe.svg?component';
	//@ts-ignore
	import Grid from '$lib/assets/grid.svg?component';
	//@ts-ignore
	import Dot from '$lib/assets/dot.svg?component';

	import Sopra1 from '$lib/assets/map/SOPRA1.svg?component';
	import Sopra2 from '$lib/assets/map/SOPRA2.svg?component';
	import Sopra3 from '$lib/assets/map/SOPRA3.svg?component';
	import Sopra4 from '$lib/assets/map/SOPRA4.svg?component';
	import Sotto1 from '$lib/assets/map/SOTTO1.svg?component';
	import Sotto2 from '$lib/assets/map/SOTTO2.svg?component';



	let mainElement: HTMLElement;
	let innerWidth: number = 0;
	let innerHeight: number = 0;
	let mobile: boolean = false;
	let scrollY: number = 0;

	let mouseX: number = 0;
	let mouseY: number = 0;

	let dx: number = 0;
	let dy: number = 0;


	onMount(() => {


		const handleScroll = () => {
			scrollY = mainElement.scrollTop;
		};

		mainElement.addEventListener('scroll', handleScroll);

		return () => {
			mainElement.removeEventListener('scroll', handleScroll);
		};
	});

	$: {
		mobile = innerWidth < 768;
		dx = (mouseX / innerWidth) - 0.5; 
		dy = (mouseY / innerHeight) - 0.5;
	}
</script>

<svelte:window bind:innerWidth bind:innerHeight bind:scrollY/>

<main bind:this={mainElement} on:mousemove={(e) => { mouseX = e.clientX; mouseY = e.clientY; console.log(dx) }}>
	<Navbar />
	<div class="map higher" style="transform: translate3d({35*dx}px, {(-scrollY * 1.25) + (35*dy)}px, 0)">
		<Sopra1 />
	</div>
	<div class="map higher" style="transform: translate3d({30*dx}px, {(-scrollY * 1.28) + (30*dy)}px, 0)">
		<Sopra2 />
	</div>
	<div class="map higher" style="transform: translate3d({25*dx}px, {(-scrollY * 1.3) + (25*dy)}px, 0)">
		<Sopra3 />
	</div>
	<div class="map higher" style="transform: translate3d({20*dx}px, {(-scrollY * 1.4) + (20*dy)}px, 0)">
		<Sopra4 />
	</div>

	<LandingPage />

	<div class="map lower" style="transform: translate3d({10*dx}px, {(-scrollY * 1.05) + (10*dy)}px, 0)">
		<Sotto2 />
	</div>
	<div class="map lower" style="transform: translate3d({5*dx}px, {(-scrollY * 1.1) + (5*dy)}px, 0)">
		<Sotto1 />
	</div>

	<Section>
		<Paragraph start={2} span={7}>
			{#if $language === 'IT'}
				In un mondo sempre più urbanizzato, la promozione della biodiversità urbana attraverso
				politiche dedicate è diventata una necessità. In questo senso, le città mettono in atto
				iniziative a diverse scale: giardini condivisi, grandi progetti di riforestazione urbana,
				parchi urbani, tetti e pareti verdi. Tuttavia, questo non è un processo senza attriti: cosa
				succede quando queste politiche colpiscono un'area e un gruppo di persone abbastanza
				ristretto?
			{:else}
				Promoting urban biodiversity through dedicated policies has become crucial in an
				increasingly urbanized world. In this regard, cities implement initiatives at various
				scales: shared gardens, large urban reforestation projects, urban parks, green roofs, and
				walls. However, promoting nature in cities is not a frictionless process: what happens when
				these policies affect a relatively small area and group of people?
			{/if}
		</Paragraph>
	</Section>
	<Section>
		<Parallax start={2} span={1} pos={scrollY * -0.1} mobile={mobile}>
			<Stripe />
		</Parallax>
		<Paragraph start={2} span={6}>
			{#if $language === 'IT'}
				La mostra esplora otto dibattiti iper-locali creati sia da politiche volte a salvaguardare
				la biodiversità, sia da interventi urbanistici che mettono in discussione la relazione tra
				la necessità di una città di cambiare e quella di preservare sistemi ecologici.
			{:else}
				The exhibition explores eight hyper-local debates generated by policies aimed at
				safeguarding biodiversity and urban interventions that question the relationship between a
				city's need to change and preserve ecological systems.
			{/if}
		</Paragraph>
		<Parallax start={3} span={2} pos={scrollY * -0.4} mobile={mobile}>
			<Dot />
		</Parallax>
	</Section>
	<Section>
		<Parallax start={4} span={2} pos={scrollY * -0.1} mobile={mobile}>
			<Grid />
		</Parallax>
		<Paragraph start={5} span={6}>
			{#if $language === 'IT'}
				Il web è stato utilizzato come una lente che permette di esplorare le dinamiche di una
				porzione del dibattito, identificando per ognuno un approccio differente: dai video YouTube
				più visti alle immagini utilizzate dalle testate online, dai commenti su Facebook alle
				trascrizioni degli incontri municipali.
			{:else}
				These dynamics have been explored through the web: from the most viewed YouTube videos to
				the images used by online news sources, from Facebook comments to transcripts of municipal
				meetings.
			{/if}
		</Paragraph>
		<Parallax start={8} span={3} pos={scrollY * -0.65} mobile={mobile}>
			<Stripe />
		</Parallax>
	</Section>
	<Section>
		<Paragraph start={3} span={7}>
			{#if $language === 'IT'}
				La mostra, promossa dal <a href="https://www.nbfc.it" target="_blank"
					>National Biodiversity Future Center</a
				>, è parte di una ricerca condotta presso il Politecnico di Milano, in cui sono stati
				coinvolti più di 50 studenti del corso di
				<a href="https://www.designdellacomunicazione.polimi.it" target="_blank"
					>Design della Comunicazione presso il Politecnico di Milano</a
				>, coordinati da <a href="https://densitydesign.org/" target="_blank">DensityDesign Lab</a>.
				Gli studenti hanno reinterpretato i frammenti più rilevanti di questi dibattiti sotto forma
				di installazioni. Il fine è quello di fornire una visione d'insieme su ogni tematica: chi
				sono gli attori coinvolti? Con quali affermazioni promuovono la loro posizione? Come
				collegano e interpretano il concetto di 'biodiversità' a queste tematiche locali?
			{:else}
				The exhibition, promoted by the <a href="https://www.nbfc.it/en" target="_blank"
					>National Biodiversity Future Center
				</a>
				, is part of a research conducted at Politecnico di Milano, involving more than 50 students from
				the
				<a href="https://www.designdellacomunicazione.polimi.it/en" target="_blank">
					Communication Design course
				</a>
				coordinated by <a href="https://densitydesign.org/" target="_blank">DensityDesign Lab</a>.
				The students reinterpreted the most relevant fragments of these debates in the form of
				installations. The goal is to provide an overview of each issue: who are the actors
				involved? What statements do they use to promote their positions? How do they connect and
				interpret the concept of biodiversity to these local issues?
			{/if}
		</Paragraph>
	</Section>
	<Section>
		<Paragraph start={2} span={6}>
			{#if $language === 'IT'}
				Le installazioni raccontano la porzione del dibattito visibile attraverso il web. Ne
				emergono delle narrazioni frammentate e talvolta contraddittorie, che ci consentono però di
				riflettere su come il tema della biodiversità incida sempre più sulle nostre vite e su come
				le ormai imprescindibili piattaforme digitali medino queste discussioni.
			{:else}
				The installations narrate the portion of the debate visible through the web. Fragmented and
				occasionally contradictory narratives emerge, allowing to reflect on how the issue of
				biodiversity increasingly affects our lives and how digital platforms mediate these
				discussions.
			{/if}
		</Paragraph>
	</Section>
	<Section>
		<h2 class="title faculty credits">
			{#if $language === 'IT'}
				Corpo Docente
			{:else}
				Faculty
			{/if}
		</h2>

		<p class="body faculty credits">
			Michele Mauri, Gabriele Colombo, Ángeles Briones, Salvatore Zingale, Elena Aversa, Arianna
			Bellantuono, Andrea Benedetti, Luca Draisci, Alessandra Facchin, Beatrice Gobbo
		</p>

		<h2 class="title nbfc credits">
			{#if $language === 'IT'}
				Coordinatori National Biodiversity Future Center
			{:else}
				National Biodiversity Future Center Coordinators
			{/if}
		</h2>
		<p class="body nbfc credits">
			<span> Massimo Labra (Università degli Studi di Milano-Bicocca) </span>
			<br />
			<span> Maria Chiara Pastore (Politecnico di Milano) </span>
		</p>
	</Section>
	<Section>
		<div id="authors">
			<h2 class="credits title" style="margin-bottom: 16px;">
				{#if $language === 'IT'}
					Autori
				{:else}
					Authors
				{/if}
			</h2>
			<p class="credits">
				Andrea Burchiani, Benedetta Riccio, Bianca Bauer, Bingru He, Carla D’Antonio, Carmen
				Framiñán, Carolina Giacomin Da Silva, Claire Capone, Corbani Federico, Daniela Muñoz, David
				Hazan, De Nicolò Alessio, Diego Valdivieso, Elisabetta Como, Filippo Roveda, Francesca
				Mattiacci, Giada Fugazzola, Giulia Costanzo, Hanya Nie, Havrylova Kseniia, Huajie Zhang,
				Javiera de la Maza, Jovana Tesic, Kalita Sudipta Sagar, Luca Bottani, Luiz Carlos De Souza
				Junior, Maciukiewicz Helena, Maher Fatemeh, Malena Paz, Martina Balducci, Michela Chignoli,
				Mo Beini, Mona Abolghasemi, Nicolás Raigoso, Nima Ahmadi, Noemi Capparelli, Oasis Mignot,
				Paola Pia Palumbo, Qin Wang, Riccardo Fregnan, Riccardo Ventura, Samuele Anzelotti, Sara
				Matilda Montorio, Shegnan Zou, Shuo Lou, Shuyu Zhang, Sofia Bonfanti, Thais De Castro Lima,
				Tommaso Prinetti, Trabattoni Marco, Vanessa Medda, Yasemin Umac, YiYou Zou, Yuhan Zhu,
				Zaiarniuk Anastasiia, Zhegnan Liu, Ziqi Huang
			</p>
		</div>
		<Footer />
	</Section>
</main>

<style>
	@import url('https://fonts.cdnfonts.com/css/switzer');

	main {
		font-family: 'Switzer', sans-serif;
		scroll-behavior: smooth;
		/*scroll-snap-type: y mandatory;*/
		overflow-y: scroll;
		height: 100vh;
		max-height: 100vh;
		max-width: 100%;
	}

	.map {
		opacity: 0.8;
		display: block;
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100vh;
		overflow: hidden;
		pointer-events: none;
	}

	:global(.map > svg) {
		transform: translate(0, -25%);
	}

	.map.lower {
		z-index: -1;
	}

	.map.higher {
		z-index: 99;
	}

	.body {
		grid-row: 3;
		align-self: start;
	}

	.faculty {
		grid-column: 2 / span 5;
	}

	.nbfc {
		grid-column: 7 / span 5;
	}

	.credits {
		font-size: 32px;
		line-height: 48px;
		margin: 0;
		font-weight: 200;
	}

	.title {
		font-weight: 500;
		grid-row: 2;
	}

	#authors {
		grid-column: 2 / span 10;
		text-align: center;
		margin: auto 0;
	}

	:global(section:nth-last-child(2) > .grid-container) {
		grid-template-rows: auto min-content min-content auto;
		grid-gap: 48px;
	}

	:global(section:last-child > .grid-container) {
		grid-template-rows: auto min-content;
		padding-top: 64px;
	}

	@media (max-width: 768px) {
		.credits {
			font-size: 24px;
			line-height: 30px;
			text-align: center;
		}

		#authors > .credits {
			font-size: 18px;
			line-height: 22px;
		}

		#authors > h2.credits {
		font-size: 24px;
		line-height: 30px;
	}

		.title.faculty {
			grid-column: 1 / 2;
			grid-row: 2;
		}

		.body.faculty {
			grid-column: 1;
			grid-row: 3;
		}

		.title.nbfc {
			grid-column: 1;
			grid-row: 5;
		}

		.body.nbfc {
			grid-column: 1;
			grid-row: 6;
		}

		:global(section:nth-last-child(2) > .grid-container) {
			display: grid;
			grid-template-columns: 1fr;
			grid-template-rows: 1fr min-content min-content 12vh min-content min-content 1fr;
			grid-gap: 12px;
			justify-content: center;
			align-items: center;
		}

		:global(section:last-child > .grid-container) {
			padding-top: 64px;
		}

		:global(.map > svg) {
			transform: translate(0, 15%) scale(1.5);
		}
	}
</style>
